# These are supported funding model platforms

github: [danceyoung]
patreon: danceyoung
open_collective: danceyoung
ko_fi: danceyoung
tidelift: npm/trycatch
custom: # Replace with a single custom sponsorship URL
