# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'trycatching' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for trycatching
  pod 'CryptoSwift'
  pod 'selectmultiplebuttons', '~> 0.0.3'
  pod 'Charts' 
  target 'trycatchingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'trycatchingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
